[program:mcp]
command=/home/casa/mcp/mcp-ckan/simple-mcp-server-test/.venv/bin/python src/server.py
environment=MCP_TRANSPORT="http",MCP_HOST="127.0.0.1",MCP_PORT="8063"
directory=/home/casa/mcp/mcp-ckan/simple-mcp-server-test
user=casa
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor-mcp.log
stderr_logfile=/var/log/supervisor-mcp.err.log
